
import { useState } from 'react';

interface SuggestionItem {
  id: string;
  type: 'update' | 'addition' | 'removal' | 'compliance';
  category: string;
  title: string;
  description: string;
  originalText?: string;
  suggestedText: string;
  priority: 'high' | 'medium' | 'low';
  status: 'pending' | 'approved' | 'rejected';
  lineNumber?: number;
}

export const useSpecificationReview = () => {
  const [suggestions, setSuggestions] = useState<SuggestionItem[]>([]);

  const generateSuggestions = (fileName: string): SuggestionItem[] => {
    // Mock suggestions with realistic line numbers that match the document content
    return [
      {
        id: '1',
        type: 'compliance',
        category: 'Building Code',
        title: 'Update IBC Reference',
        description: 'The International Building Code reference is outdated and should be updated to IBC 2021.',
        originalText: 'IBC 2018, Section 705.8',
        suggestedText: 'IBC 2021, Section 705.8',
        priority: 'high',
        status: 'pending',
        lineNumber: 21
      },
      {
        id: '2',
        type: 'update',
        category: 'Manufacturer',
        title: 'Update Armstrong Product',
        description: 'Armstrong Mineral Fiber tiles have been discontinued. Suggest current alternatives.',
        originalText: 'Armstrong Mineral Fiber Ceiling Tiles, Model 1234',
        suggestedText: 'Armstrong Ultima Vector Ceiling Tiles, Model 5678 or USG Mars Climaplus',
        priority: 'medium',
        status: 'pending',
        lineNumber: 26
      },
      {
        id: '3',
        type: 'addition',
        category: 'Sustainability',
        title: 'Add LEED Requirements',
        description: 'Include LEED v4.1 recycled content requirements for better sustainability compliance.',
        suggestedText: 'Materials shall contain minimum 50% recycled content per LEED v4.1 MR Credit: Building Product Disclosure and Optimization.',
        priority: 'medium',
        status: 'pending',
        lineNumber: 32
      },
      {
        id: '4',
        type: 'compliance',
        category: 'Material Standard',
        title: 'Update ASTM Standard',
        description: 'ASTM E84 standard reference is outdated.',
        originalText: 'ASTM E84-20',
        suggestedText: 'ASTM E84-23',
        priority: 'high',
        status: 'pending',
        lineNumber: 29
      },
      {
        id: '5',
        type: 'update',
        category: 'Performance',
        title: 'Improve R-Value Specification',
        description: 'Current R-value specification does not meet energy efficiency requirements.',
        originalText: 'R-30 minimum',
        suggestedText: 'R-38 minimum per current energy codes',
        priority: 'high',
        status: 'pending',
        lineNumber: 28
      }
    ];
  };

  const approveSuggestion = (suggestionId: string) => {
    setSuggestions(prev => 
      prev.map(suggestion => 
        suggestion.id === suggestionId 
          ? { ...suggestion, status: 'approved' as const }
          : suggestion
      )
    );
  };

  const rejectSuggestion = (suggestionId: string) => {
    setSuggestions(prev => 
      prev.map(suggestion => 
        suggestion.id === suggestionId 
          ? { ...suggestion, status: 'rejected' as const }
          : suggestion
      )
    );
  };

  const approveAllSuggestions = () => {
    setSuggestions(prev => 
      prev.map(suggestion => 
        suggestion.status === 'pending'
          ? { ...suggestion, status: 'approved' as const }
          : suggestion
      )
    );
  };

  const downloadRevisedSpecification = (fileName: string, approvedSuggestions: SuggestionItem[]) => {
    // Generate revised document content
    const revisedContent = `
# Revised Specification: ${fileName}

## Applied Changes:
${approvedSuggestions.map(suggestion => `
- ${suggestion.title}: ${suggestion.description}
  ${suggestion.originalText ? `Original: ${suggestion.originalText}` : ''}
  Revised: ${suggestion.suggestedText}
`).join('\n')}

## Full Specification Content:
[This would contain the complete specification with all approved changes applied]

Generated by AI Specification Review System
Date: ${new Date().toLocaleDateString()}
    `;

    const blob = new Blob([revisedContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName.replace('.', '_revised.')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return {
    suggestions,
    setSuggestions,
    generateSuggestions,
    approveSuggestion,
    rejectSuggestion,
    approveAllSuggestions,
    downloadRevisedSpecification
  };
};
