// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrxefmevbihkhognczgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyeGVmbWV2Ymloa2hvZ25jemdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjQ4ODQsImV4cCI6MjA2NTg0MDg4NH0.4yxXZgZndIBj0djefuQDVOsVYmHHgMakb_ZUCsv_5JA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);